#ifndef INDEX_HTML_H
#define INDEX_HTML_H

const char* index_html =
"<!DOCTYPE html>\n"
"<html lang=\"pt-BR\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Estação Meteorológica</title>\n"
"    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap\" rel=\"stylesheet\">\n"
"    <link href='https://cdn.boxicons.com/fonts/basic/boxicons.min.css' rel='stylesheet'>\n"
"    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
"    <script src=\"https://cdn.jsdelivr.net/npm/apexcharts\"></script>\n"
"    <style>\n"
"        body {font-family: \"Roboto Mono\", monospace;background-color: #000;color: #fafafa;}\n"
"        .data-card {background-color: #0a0a0a;border-radius: 0.75rem;padding: 1.5rem;border: 1px solid #262626;}\n"
"        .btn-card {\n"
"            background-color: #000;\n"
"            color: #fafafa;\n"
"            border: none;\n"
"            padding: 0.5rem 2rem;\n"
"            border-radius: 0.75rem;\n"
"            border: 1px solid #262626;\n"
"            text-align: center;\n"
"            text-decoration: none;\n"
"            display: inline-block;\n"
"            font-size: 0.8rem;\n"
"        }\n"
"        .active {background-color: #262626;}\n"
"    </style>\n"
"</head>\n"
"<body class=\"p-4 md:p-8 lg:p-16\">\n"
"    <div class=\"max-w-7xl mx-auto\">\n"
"        <section class=\"mb-8 mt-12\">\n"
"            <div class=\"grid grid-cols-1 grid-rows-1 md:grid-cols-2 gap-6\">\n"
"                <div class=\"data-card flex justify-center items-center gap-2\">\n"
"                    <i class='bxr bx-clock-11 text-3xl md:text-5xl'></i> \n"
"                    <p id='timestamp-data' class='text-3xl md:text-5xl font-bold'>15:30:34</p>\n"
"                </div>\n"
"                <div class=\"grid grid-cols-1 grid-rows-1 md:grid-cols-2 md:grid-rows-2 gap-6\">\n"
"                    <div class=\"data-card text-left\">\n"
"                        <p class=\"text-base font-medium text-white flex justify-items-center items-center gap-2\">\n"
"                            <i class='bxr bx-tachometer'></i>\n"
"                            <span>Pressão Atmosférica</span>\n"
"                        </p>\n"
"                        <p id=\"pressure-box\" class=\"text-2xl font-bold text-green-500 mt-2\">20 hPa</p>\n"
"                    </div>\n"
"                    <div class=\"data-card text-left\">\n"
"                        <p class=\"text-base font-medium text-white flex justify-items-center items-center gap-2\">\n"
"                            <i class='bxr bx-thermometer'></i>\n"
"                            <span>Temperatura</span>\n"
"                        </p>\n"
"                        <p id=\"temperature-box\" class=\"text-2xl font-bold text-green-500 mt-2 mb-2\">45.6 ºC</p>\n"
"                        <span id=\"temperature-limits-box\" class=\"bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-lg dark:bg-blue-900 dark:text-blue-300\">MIN: 15 ºC | MAX: 70ºC m</span>\n"
"                    </div>\n"
"                    <div class=\"data-card text-left\">\n"
"                        <p class=\"text-base font-medium text-white flex justify-items-center items-center gap-2\">\n"
"                            <i class='bxr bx-water-drop-alt'></i>\n"
"                            <span>Umidade</span>\n"
"                        </p>\n"
"                        <p id=\"humidity-box\" class=\"text-2xl font-bold text-green-500 mt-2 mb-2\">20%</p>\n"
"                        <span id=\"humidity-limits-box\" class=\"bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-lg dark:bg-blue-900 dark:text-blue-300\">MIN: 23% | MAX: 68%</span>\n"
"                    </div>\n"
"                    <div class=\"data-card text-left\">\n"
"                        <p class=\"text-base font-medium text-white flex justify-items-center items-center gap-2\">\n"
"                            <i class='bxr bx-mountain-peak'></i>\n"
"                            <span>Altitude</span>\n"
"                        </p>\n"
"                        <p id=\"altitude-box\" class=\"text-2xl font-bold text-green-500 mt-2\">325 m</p>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"<div id=\"alert-box\" class=\"p-4 mb-4 text-red-800 border border-[#550606] rounded-lg bg-[#0f0000] hidden\" role=\"alert\">"
    "<div class=\"flex items-center\">"
        "<svg class=\"shrink-0 w-4 h-4 me-2\" aria-hidden=\"true\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 20 20\">"
        "<path d=\"M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z\"></path>"
        "</svg>"
        "<span class=\"sr-only\">Info</span>"
        "<h3 class=\"text-lg font-medium\">Alerta</h3>"
    "</div>"
    "<div id=\"alert-box-msg\" class=\"mt-2 mb-4 text-sm\"></div>"
"</div>\n"
"        <section class=\"mb-8\">\n"
"            <div class=\"text-xl font-medium text-white flex justify-items-center items-center gap-2 mb-4\">\n"
"                <i class='bxr bx-chart-line'></i>\n"
"                <h2>Histórico de Medições</h2>\n"
"            </div>\n"
"            <div class=\"data-card\">\n"
"                <div class=\"flex flex-col md:flex-row justify-between items-start md:items-center mb-4\">\n"
"                    <div id=\"plots-card-control\" class=\"grid grid-cols-1 gap-2 w-full md:grid-cols-3\">\n"
"                        <button data-control=\"temperature\" class=\"btn-card plot-btn active\">Temperatura</button>\n"
"                        <button data-control=\"pressure\" class=\"btn-card plot-btn\">Pressão</button>\n"
"                        <button data-control=\"humidity\" class=\"btn-card plot-btn\">Umidade</button>\n"
"                    </div>\n"
"                </div>\n"
"                <div id=\"plots-card\"></div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <section class=\"mb-8\">\n"
"            <div class=\"text-xl font-medium text-white flex justify-items-center items-center gap-2 mb-4\">\n"
"                <i class='bxr bx-ruler'></i>\n"
"                <h2>Definição de Limites</h2>\n"
"            </div>\n"
"            <div class=\"grid grid-cols-1 gap-6\">\n"
"                <div class=\"data-card grid grid-cols-1 gap-4\">\n"
"                    <div class=\"grid grid-cols-1 gap-2\">\n"
"                        <div class=\"w-full\">\n"
"                            <label for=\"temperature-min\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Temperatura mínima</label>\n"
"                            <input type=\"number\" name=\"temperature-min\" id=\"temperature-min\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"20 ºC\" required=\"\">\n"
"                        </div>\n"
"                        <div class=\"w-full\">\n"
"                            <label for=\"temperature-max\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Temperatura máxima</label>\n"
"                            <input type=\"number\" name=\"temperature-max\" id=\"temperature-max\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"45 ºC\" required=\"\">\n"
"                        </div>\n"
"                   </div>\n"
"                    <div class=\"mt-4 grid grid-cols-1 gap-2\">\n"
"                        <div class=\"w-full\">\n"
"                            <label for=\"humidity-min\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Umidade mínima</label>\n"
"                            <input type=\"number\" name=\"humidity-min\" id=\"humidity-min\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"20%\" required=\"\">\n"
"                        </div>\n"
"                        <div class=\"w-full\">\n"
"                            <label for=\"humidity-max\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Umidade máxima</label>\n"
"                            <input type=\"number\" name=\"humidity-max\" id=\"humidity-max\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"65%\" required=\"\">\n"
"                        </div>\n"
"                    </div>\n"
"                    <div class=\"w-full md:flex md:justify-end\">\n"
"                        <button id=\"btn-sensors-levels\" class=\"btn-card hover:bg-white hover:text-black hover:border-white w-full md:w-auto\"><i class='bxr  bx-refresh-cw'  ></i> Atualizar limites</button>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"<section class=\"mb-8\">"
    "<div class=\"text-xl font-medium text-white flex justify-items-center items-center gap-2 mb-4\">"
        "<i class='bxr bx-ruler'></i>"
        "<h2>Definição de Offsets</h2>"
    "</div>"
    "<div class=\"grid grid-cols-1 gap-6\">"
        "<div class=\"data-card grid grid-cols-1 gap-4\">"
            "<div class=\"grid grid-cols-1 gap-2\">"
                "<div class=\"w-full\">"
                    "<label for=\"temperature-offset\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Temperatura</label>"
                    "<input type=\"number\" name=\"temperature-offset\" id=\"temperature-offset\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"5 ºC\" required=\"\">"
                "</div>"
            "</div>"
            "<div class=\"mt-4 grid grid-cols-1 gap-2\">"
                "<div class=\"w-full\">"
                    "<label for=\"humidity-offset\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Umidade</label>"
                    "<input type=\"number\" name=\"humidity-offset\" id=\"humidity-offset\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"7%\" required=\"\">"
                "</div>"
                "<div class=\"w-full\">"
                    "<label for=\"pressure-offset\" class=\"block mb-2 text-sm font-medium text-gray-900 dark:text-white\">Pressão</label>"
                    "<input type=\"number\" name=\"pressure-offset\" id=\"pressure-offset\" class=\"input-limit bg-[#000] border border-[#262626] text-gray-900 text-sm rounded-lg block w-full p-2.5 outline-none focus-within:border-gray-700 text-white\" placeholder=\"1 hPa\" required=\"\">"
                "</div>"
            "</div>"
            "<div class=\"w-full md:flex md:justify-end\">"
                "<button id=\"btn-offset\" class=\"btn-card hover:bg-white hover:text-black hover:border-white w-full md:w-auto\"><i class='bxr  bx-refresh-cw'></i> Adicionar Offests</button>"
            "</div>"
        "</div>"
    "</div>"
"</section>"
"    </div>\n"
"<script src=\"https://cdn.jsdelivr.net/gh/GabrielShiva/gabriel_scripts@main/script_v1_8.js\"></script>\n"
"</body>\n"
"</html>";

#endif
